apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gameboard-api.fullname" . }}
  labels:
    {{- include "gameboard-api.labels" . | nindent 4 }}
data:
  ca-cert.crt: |
{{ .Values.cacert | indent 4 }}
  start.sh: |
    #!/bin/sh

    cp /start/ca-cert.crt /usr/local/share/ca-certificates
    update-ca-certificates
    cd /app
    dotnet Gameboard.Api.dll

  job.sh: |-
    #!/bin/sh

    giturl={{ .Values.giturl }}
    branch={{ .Values.gitbranch }}
    poll={{ .Values.pollInterval | default 10 }}

    if [ -n "$giturl" ]; then

      repo=$(echo $giturl | awk -F/ '{print $NF}' | sed  s,.git,,)

      ## get tools
      apk update && apk add git || exit 1

      {{- if .Values.cacert }}
      # update CA trust
      /entry.d/update-trust.sh
      {{- end }}

      ## get source
      cd /docs
      git clone $giturl .
      if [ -n "$branch" ]; then
        git checkout $branch
        git pull
      fi

      echo "*/$poll * * * * cd /docs && git pull" >> /etc/crontabs/root

    fi

    crond -f -d8 > /proc/1/fd/1 2> /proc/1/fd/2
