apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "staticweb.fullname" . }}
  labels:
    {{- include "staticweb.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "staticweb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        consistency/unique: {{ randAlphaNum 8 | quote }}
    {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "staticweb.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "staticweb.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "nginx:alpine"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /docker-entrypoint.d/30-configure-nginx.sh
              name: {{ include "staticweb.name" . }}-entry
              subPath: nginx.sh
            {{- if .Values.cacert }}
            - mountPath: /docker-entrypoint.d/25-update-trust.sh
              name: {{ include "staticweb.name" . }}-entry
              subPath: update-trust.sh
            {{- end }}
            - mountPath: /etc/nginx/conf.d/default.conf
              name: {{ include "staticweb.name" . }}-entry
              subPath: nginx-default.conf
            {{- if or .Values.giturl (or .Values.storage.existing .Values.storage.size) }}
            - mountPath: /html
              name: {{ include "staticweb.name" . }}-vol
              subPath: {{ include "staticweb.fullname" . }}
            {{- else }}
            - mountPath: /html
              name: {{ include "staticweb.name" . }}-docs
            {{- end }}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.giturl }}
        - name: {{ .Chart.Name }}-job
          image: alpine
          command: [ "/entry.d/job.sh" ]
          volumeMounts:
            - mountPath: /entry.d
              name: {{ include "staticweb.name" . }}-entry
            - mountPath: /html
              name: {{ include "staticweb.name" . }}-vol
              subPath: {{ include "staticweb.fullname" . }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: {{ include "staticweb.name" . }}-entry
        configMap:
          name: {{ include "staticweb.fullname" . }}
          defaultMode: 0775
      - name: {{ include "staticweb.name" . }}-docs
        configMap:
          name: {{ include "staticweb.fullname" . }}-docs
      {{- if .Values.storage.existing }}
      - name: {{ include "staticweb.name" . }}-vol
        persistentVolumeClaim:
          claimName: {{ .Values.storage.existing }}
      {{- else if .Values.storage.size }}
      - name: {{ include "staticweb.name" . }}-vol
        persistentVolumeClaim:
          claimName: {{ include "staticweb.fullname" . }}
      {{- else }}
      - name: {{ include "staticweb.name" . }}-vol
        emptyDir: {}
      {{- end }}
